services:
  caddy:
    image: caddy:2-alpine
    restart: unless-stopped

    depends_on:
      - frontend
      - backend

    ports:
      - "80:80"
      - "443:443"

    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./uploads:/srv/uploads:ro
      - caddy_data:/data
      - caddy_config:/config

    networks:
      - aerox_net

volumes:
  caddy_data:
  caddy_config: